### PR TITLE
Hung updates AboutUs

### PR DESCRIPTION
**Pull request by hungkhoaitay**

### CODE REVIEW

**Comment by jayasting98** [comment]
Don't forget to add your [Project Portfolio Page](https://nus-cs2103-ay2122s1.github.io/website/admin/tp-deliverables.html#deliverable-project-portfolio-page-ppp). Also, may I know why there are changes to the `puml` files?

**Comment by hungkhoaitay** [comment]
> Don't forget to add your [Project Portfolio Page](https://nus-cs2103-ay2122s1.github.io/website/admin/tp-deliverables.html#deliverable-project-portfolio-page-ppp). Also, may I know why there are changes to the `puml` files?

I think it is for Documentation Diagrams, I implemented it last week but didn't make the pull request. 
https://nus-cs2103-ay2122s1.github.io/tp/Documentation.html

**Comment by jayasting98** [comment]
Oh, are we supposed to touch the diagrams yet? Also, I think those two files already exist and are already part of the project; [here is the style file](https://github.com/AY2122S1-CS2103T-W17-3/tp/blob/master/docs/diagrams/style.puml) and [here is the undo sequence diagram](https://github.com/AY2122S1-CS2103T-W17-3/tp/blob/master/docs/diagrams/UndoSequenceDiagram.puml). You can also see the undo sequence diagram in [this section in the Developer Guide](https://ay2122s1-cs2103t-w17-3.github.io/tp/DeveloperGuide.html#proposed-undoredo-feature) too. Were you planning to change those files? I think if you want to do that, you should update those files directly instead of adding new files. Also, maybe if you do still want to add the new files, maybe they should be in the `docs/diagrams` folder instead?

I am not sure if this needs to be done though. I think maybe we need to ask the other members. I am fine with your changes to the AboutUs page though, but you still need to add the Project Portfolio Page. Maybe you should do a separate PR for the diagrams, and just leave only the AboutUs stuff in this PR. After you do that, then I can probably merge your AboutUs PR.

**Comment by hungkhoaitay** [comment]
Yea @jayasting98, you are right. I have removed the two unnecessary files, and added the Portfolio :smile:

**Review by jayasting98 — APPROVED** [review]
Ok, I think it should be fine now; I don't see anything else. Probably LGTM.

**Pull request merged**
